GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzYzNTk5LTIzMGQtNDMxYy05NzRiLTNjOTVlYmMwN2ZlZSIsInVzZXJuYW1lIjoicGF3IiwiaWF0IjoxNjA5NjE0MTUwLCJleHAiOjE2MDk2MTQxOTB9.PideQZGcg7F9TTLeWk1vdt5TslLMmrj0P4MaqXhJ5Aw

###
POST http://localhost:3000/changePassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzYzNTk5LTIzMGQtNDMxYy05NzRiLTNjOTVlYmMwN2ZlZSIsInVzZXJuYW1lIjoicGF3IiwiaWF0IjoxNjA5NjE0NDM2LCJleHAiOjE2MDk2MTQ0NzZ9.PRrWo_ELcx4gAHmcZkTeoBtvZpFhXrQhobOiRMs7nw4
Content-Type: application/json

{
   "newPassword":"prabhat"
}
####

POST http://localhost:3000/exists
Content-Type: application/json

{
   "email":"prabhat"
}


###
GET http://localhost:3000/recover?id=62363599-230d-431c-974b-3c95ebc07fee&recoveryKey=610862
###


POST http://localhost:3000/recover
Content-Type: application/json

{
     "email":"paw@gmail.com"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
   "email":"paw@gmail.com",
  "password":"pawan"
}

###
POST http://localhost:3000/token
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzYzNTk5LTIzMGQtNDMxYy05NzRiLTNjOTVlYmMwN2ZlZSIsInVzZXJuYW1lIjoicGF3IiwiZGlzcGxheU5hbWUiOiJQYXdhbiBCaGF0dGEiLCJpYXQiOjE2MDk2MTQxMjR9.quCBGDHtRM45xGMsW8Y1qVOGhhOzs9DypjBxoIPcWrM"
}


###

POST http://localhost:3000/register
Content-Type: application/json

{
  "username":"paw",
  "email":"paw@gmail.com",
  "password":"pawan",
  "country":"Nepal",
  "displayName":"Pawan Bhatta"
}

###
POST http://localhost:3000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdjZTllYzRhLTY1ZmEtNDA0YS1iYzhmLTBiNTQ0OWEyOWIwOSIsInVzZXJuYW1lIjoicGF3YW5oaCIsImRpc3BsYXlOYW1lIjoiUGF3YW4gQmhhdHRhIiwiaWF0IjoxNjA5NDczMzA5fQ.Z6eWKNFSZ_hGje2P-6bI1fuS-YaG-96xii1vY4uAhUg",
  "deleteAllSession":"true"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "Jim"
}