GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxNDExZDIxLTE0ZTItNGM0NC1hMTUyLTg2ZjEwYjI5Mzc1NyIsInVzZXJuYW1lIjoicGF3YW4xN3Nqam5obTgiLCJpYXQiOjE2MDkxOTQxMzEsImV4cCI6MTYwOTE5NDE1MX0.LvsGZU0JnwY81Ahz84oJzJ0OEdFpk6e6lN0RX0a1Uu8

###

POST http://localhost:3000/login
Content-Type: application/json

{
   "username":"pawan",
  "password":"pawan"
}

###
POST http://localhost:3000/token
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxNDExZDIxLTE0ZTItNGM0NC1hMTUyLTg2ZjEwYjI5Mzc1NyIsInVzZXJuYW1lIjoicGF3YW4xN3Nqam5obTgiLCJkaXNwbGF5TmFtZSI6IlBhd2FuIEJoYXR0YSIsImlhdCI6MTYwOTE5NDA4Nn0.uJ_3Y_WJeCyuQcE3BwGlPcaqPTJMDFawdGq75e9FceA"
}


###

POST http://localhost:3000/register
Content-Type: application/json

{
  "username":"pawan",
  "email":"pawan@gmail.com",
  "password":"pawan",
  "country":"Nepal",
  "displayName":"Pawan Bhatta"
}

###
POST http://localhost:3000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhYjBjOGY3LTc0MmQtNGIwOS1hYzdlLWRjYmVmY2Y4ODZiOCIsInVzZXJuYW1lIjoicGF3YW4xN204IiwiZGlzcGxheU5hbWUiOiJQcmFiaGF0IEJoYXR0YSIsImlhdCI6MTYwOTE5MDMxNX0.PHAS5ibrQhqbG5fEjl-5UKGgKtus8arKURH5o-W6GZo"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "Jim"
}